# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!
target 'Dabbles' do
  #pod 'FSCalendar'
  # add the Firebase pods
  #pod 'Firebase/Auth'
  #pod 'Firebase/Firestore'
end
